title: "Mina Protocolの歩き方"
summary: "ゼロ知識証明をベースとしたブロックチェーンMina Protocolについて、基礎的な知識や開発エコシステムから基本的な実装方法までを解説します。"
topics: ["ブロックチェーン", "Mina Protocol", "ゼロ知識証明"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - about-this-book
  - mina-protocol-and-zk
  - developement-ecosystem
